### ISSUE TITLE
[Critical] GUI filebrowser bug

### ISSUE THREAD

**Issue by Mystro256** [Mystro256/wiisxr#12]
A bug, which needs to be direly fixed, is a break in the GUI file browser if large portions of code are changed. It seems to cause the files to be treated as folders and folders to be treated as files. For example, when opening a folder, an error says "could not open ISO file", which closes the browser, and something similar happens to iso files. **EDIT: I can only reproduce this with the SD card menu at the momment**

I mentioned this in Issue #8 , but I've managed to reproduce the error. If the bug can be solved, it would reduce the need to throw out the GUI code and redoing it as suggested in Issue #8 . This currently blocks Issue #2 , #4 , #5 , Issue #6 and possibly #7 .

The best way to reproduce it would be either to checkout and build the **gxrender** branch (in which the GPU code is being overhauled, thus would cause this bug) or turning on the _-ffast-math_ flag by adding it to "CFLAGS" in Gamecube/Makefile_Wii (or GC if desired).

**Comment by roflcopter777** [comment]
Have you contacted Emukidid, Ekeeke or Extrems by any chance? They originally worked on WiiSX, so maybe they could lend some insight on what's going on with the GUI?

**Comment by Mystro256** [comment]
Hmmm, good point.

I'll have to track down their email addresses when I have time.

**Comment by roflcopter777** [comment]
Okay, that's fine

**Comment by Mystro256** [comment]
Found it, see 2d9838ab66226cf82f3e4876a03f0877b3723475
