### ISSUE TITLE
gamecube releases?

### ISSUE THREAD

**Issue by Deadpixel66** [Mystro256/wiisxr#17]
Do you think you can put the compiled gamecube wiisxr in the releases? I tried to compile it but I failed :/

**Comment by Mystro256** [comment]
Honestly, I would personally like to drop gamecube support, as I do not have a working system to test it on or time to work on both Wii and Gamecube. If anyone is interested in fixing the gamecube build, I will reopen this. (likely just needs some ifdef's to fix it)
