### ISSUE TITLE
[Regression] Freeze during startup via BIOS

### ISSUE THREAD

**Issue by n00ris** [Mystro256/wiisxr#23]
Hello,
after commit 
fdb93be2974a79f27e4dd3de1fae021b9dcc71b4 (Update README to include libfatmod (ustealth) 
I ran into a regression.

If I boot via BIOS, the last available dol  
[ from commit 9519304230c369fa0284c14843a231c9bc62d2c5 (Revert ppc for now) ]
freeze at BIOS startup (at the moment the big P is displayed, in other words, it does not proceed to load the game)

fdb93be2974a79f27e4dd3de1fae021b9dcc71b4 working fine (at least the start)

Tried some dols from the commits in between, but they seem to be broken (Freeze with constant sound directly after I try to start a game)

**Comment by Mystro256** [comment]
Seems I missed something in the revert commit.

Fixed it in the code, so I'll close it for now. Feel free to reopen this if it's not fixed after I release version 2.3.
