### ISSUE TITLE
Important!!!

### ISSUE THREAD

**Issue by darkto62** [Mystro256/wiisxr#25]
Hi, Mystro256, there a issue in the compatibility LIST!!

Each "game region" is neccesary for the compatibility list, for that games dont work and another versions of regions yes...

example:
THE ONLY "Crash team racing" that work is the game region: SCUS-99459  [THE GAME DEMO]
add the "Region" in the Compatibility list, i will update the "info" of the games that i have tested putting the regions.

sorry for baad english

**Comment by leodexe** [comment]
This game is well known to have issues with most emulators, not only WiiSXR. It is related with the SPUsync function, that handles some sort of audio streaming that most emulators can't deal with properly. And also, the correct region is SCUS-94459. You can test this by loading the game on any emulator (or any that show ROM/ISO Info)

**Comment by Mystro256** [comment]
I don't understand the issue here, there is a region column? If someone hasn't entered a specific version, please feel free to make an update.
