### ISSUE TITLE
poject is dead or still developed?

### ISSUE THREAD

**Issue by migot1993** [Mystro256/wiisxr#28]
Hi I want ask becasue I'am new here and i dont know. I can test the games are not on the compatibility list, but I have to know that the project is developed.

**Comment by Mystro256** [comment]
I wouldn't say it's dead, just heavily stalled. Unfortunately I don't have
a lot of time to give and I appear to be the only dev interested in working
on it.

**Comment by roflcopter777** [comment]
What can we do to help others get interested?

**Comment by migot1993** [comment]
Thanks for answer.
I understand everyone has their own life and personal affairs. I wanted to make sure only if the project is in progress or abandoned but anyway thanks for all your time and work. I appreciate what you're doing

If possible I can help you in every possible way if if I'll be able

**Comment by Mystro256** [comment]
@migot1993 Feel free to test games and leave your comments in the compatibility list.
Truthfully, the biggest form of help I need is dev help, i.e. fix bugs and whatnot.
I managed to spend some time on the weekend to close 4 issues, but my time is limited and this project is likely going to be moving at a snail's pace for the time being.
