### ISSUE TITLE
Crash when trying to go up a folder

### ISSUE THREAD

**Issue by Monsterray** [Mystro256/wiisxr#29]
When I try to click the one or two dots in the iso chooser the app crashes and sends me back to the homebrew browser.

Here is a short video of what im talking about.

https://dl.dropboxusercontent.com/u/44123755/MOV00016.AVI

**Comment by Mystro256** [comment]
I think i just fixed this, it will be included in the next version. Is your device formated in FAT?

**Comment by Mystro256** [comment]
Should be fixed in the code, so I'll close it for now.
Feel free to reopen if you still have issues after I release version 2.3

**Comment by Mystro256** [comment]
I think i just fixed this, it will be included in the next version. Is your
device formated in FAT?
