### ISSUE TITLE
Better Logo

### ISSUE THREAD

**Issue by Mystro256** [Mystro256/wiisxr#3]
I put a very temporary logo in for now, but it's very ugly, and personally, I would like a new one.

Note that WiiSX and the WiiSX logo are trademarks of the Wii64 Team, thus cannot be used in this fork.

Feel free to comment or post an issue if there is still remnant branding or logos.

Also, feel free to make a new logo and submit it! :)

**Comment by iiiGerardoiii** [comment]
**I just made these:**
![wiisxrlogo1](https://cloud.githubusercontent.com/assets/6264194/11265759/90f92e5e-8e64-11e5-87a8-5ac4af705f13.png) ![wiisxrlogo2](https://cloud.githubusercontent.com/assets/6264194/11265763/95bacc5e-8e64-11e5-9c67-79289b4a23ab.png)
Let me know what you think.

**Comment by Mystro256** [comment]
I like the second one (yellow R) a lot.

Are you able to make it with a transparent background?

**Comment by Mystro256** [comment]
Scratch that, I changed my mind. Can I commit the second image and credit you for the image?

**Comment by iiiGerardoiii** [comment]
Sure no prob

Here's the vectorized version if you wanna do some changes or export it to a higher res:
[wiisxrlogo2.pdf](https://github.com/Mystro256/wiisxr/files/39118/wiisxrlogo2.pdf)

**Comment by Mystro256** [comment]
Thanks!
