### ISSUE TITLE
Black screen when exiting when loaded from a forwarder (vWii)

### ISSUE THREAD

**Issue by MeisterLLD** [Mystro256/wiisxr#49]
When quitting WiiSXR started from a forwarder in the vWii, it just goes to a black screen.
When loaded from Homebrew channel it quits fine though.

**Comment by pawhtiobo** [comment]
Hi,

I share the same thing with a regular Wii, but its OK, because this emulator is great! 

Regards,

**Comment by Mystro256** [comment]
The WiiSX forwarders do not work correctly with WiiSXR, please do not use them.

See #15, I have been meaning to get around to this, but I haven't even had time to release v2.3, which is long overdue.
