### ISSUE TITLE
Subfolder Support

### ISSUE THREAD

**Issue by jrom89** [Mystro256/wiisxr#51]
Currently, WiiSX-R doesn't know how to open a subfolder when browsing SD/USB for a game to load. As a result, all games and their associated .cue/.bin/track files have to sit in the same folder together, making it cumbersome to select a game to load. It would be much better to be able to organize these games in subfolders.

thanks!

**Comment by Mystro256** [comment]
This was a bug in the file browser, I fixed it in the code but I haven't made a new build yet. Hold tight, I have to fix my build system first.
