### ISSUE TITLE
Crash Team Racing (PAL/NTSC) stucks at intro screen.

### ISSUE THREAD

**Issue by BellezaEmporium** [Mystro256/wiisxr#61]
Hello,

I know you've took development again and thanks for that !

But I have a little problem with WiiSXR regarding Crash Team Racing.

Both (even when patched, all versions and even EDC or not EDC) does not work.

Using FIX94's modified-for-WiiVC beta 2.2 version.

Hope I'm not bothering too much.

Cordially,
S.A.

**Comment by Mystro256** [comment]
I think this is a duplicate of #40 

Please re-open if I'm incorrect.
