### ISSUE TITLE
About beta 2.3 - Will test

### ISSUE THREAD

**Issue by BellezaEmporium** [Mystro256/wiisxr#62]
Hello,

Since you've released v2.3, I thought I could try by testing your gamepad support. So I will inject beta 2.3 onto a homebrew and tell you the results I have.

Until then, take care and awesome work.

S.A.

**Comment by BellezaEmporium** [comment]
Using the v2.2 FIX94 WiiVC forwarder, Gamepad support works.

I do not know however if you haven't changed the 2.2 beta on the credits.

**Comment by Mystro256** [comment]
Ah yes, let me correct that, I thought I did so. I also forgot to add FIX94 to the credits.

**Comment by roflcopter777** [comment]
@Mystro256  Any possible insights on the screen tearing?
https://github.com/Mystro256/wiisxr/issues/59

**Comment by BellezaEmporium** [comment]
Haha well that's nice !

Your emulator is good right now. And sorry to bother you @Mystro256 but have you got time to check my issue about CTR #61 ? Will be nice !

Thanks again.

**Comment by Mystro256** [comment]
Fixed the credits issue, it now reports the correct version.

As for the other issues, I'll try to look into them, but no promises.

**Comment by BellezaEmporium** [comment]
Okay, hope that it can helps for my issue : SPUsync conflicts with CTR.
