### ISSUE TITLE
UStealth support for Wii U

### ISSUE THREAD

**Issue by cucholix** [Mystro256/wiisxr#9]
Replacing by this libfat library
http://www.mediafire.com/?9d1ffxo16kc1gmq

UStealth hides HDD from Wii U OS to avoid getting the format messages upon boot.
More info:
http://gbatemp.net/threads/ustealth-wii-u-format-disk-nag-workaround.352786/page-12#post-4988611

I successfully compiled it with the new libfat http://www.mediafire.com/download/in8k6lfeurfi7bk/WiiSX(UStealth).dol

:)

**Comment by Mystro256** [comment]
Sounds good, I'll compile it with this on my next build

**Comment by Mystro256** [comment]
Done, please let me know if it doesn't work
